export const SAMPLE_ACTION = 'SAMPLE_ACTION';

//Covid Track
export const COVID_DATA_FETCH_START = 'COVID_DATA_FETCH_START';
export const COVID_DATA_FETCH_NO_CONNECTION = 'COVID_DATA_FETCH_NO_CONNECTION';
export const COVID_DATA_FETCH_SUCCESS = 'COVID_DATA_FETCH_SUCCESS';
export const COVID_DATA_FETCH_ERROR = 'COVID_DATA_FETCH_ERROR';
